admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
curation_repository_path: /home/emarch/Documents/phi_packages/Datacur_bkup/curate/curation
homepage: homepage@domain.org
provider: My Organization
