admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
curation_repository_path: /home/emarch/Documents/Inditex/CII/proyecto2024/figura_paper_ED/curation
homepage: homepage@domain.org
provider: My Organization
