admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
curation_repository_path: /home/eric/phi_lab/datacuration_paper/paper_curation/curation
homepage: homepage@domain.org
provider: My Organization
